# Generated by Django 4.1.6 on 2023-03-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
